
FROM node:20-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY --from=game-ws-protocol / /packages/game-ws-protocol

RUN cd /packages/game-ws-protocol \
	&& if [ -f package-lock.json ]; then npm ci; else npm install; fi \
	&& npm run build

COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose dev server port
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
