api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        domains:
          - main: localhost
            sans:
              - "*.localhost"
              - "127.0.0.1"
          - main: ${DOMAIN}
            sans:
              - "*.${DOMAIN}"
  metrics:
    address: ":8082"

providers:
  file:
    directory: /etc/traefik/conf
    watch: true

tls:
  certificates:
    - certFile: /certs/localhost-cert.pem
      keyFile: /certs/localhost-key.pem
    - certFile: /certs/cloudflare-origin-cert.pem
      keyFile: /certs/cloudflare-origin-key.pem

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
